Validate that no files were changed during build

diff --git a/.vsts/distribution.yml b/.vsts/distribution.yml
--- a/.vsts/distribution.yml
+++ b/.vsts/distribution.yml
@@ -41,6 +41,16 @@ stages:
         steps:
           - template: ./linux/distribution.yml
 
+          - script: |
+              set -e
+              changed=`git status | grep 'modified:' | wc -l`
+              if [ "$changed" -ne "0" ]; then
+                echo "Changes detected. Pipeline failed"
+                exit 1
+              fi
+            workingDirectory: $(Build.ArtifactStagingDirectory)/BatchExplorer
+            displayName: Validate no files changed on build
+
       - job: MacOS
         dependsOn: DownloadArtifacts
         pool:
