Print out git diff for debugging

diff --git a/.vsts/linux/ci.yml b/.vsts/linux/ci.yml
--- a/.vsts/linux/ci.yml
+++ b/.vsts/linux/ci.yml
@@ -11,18 +11,19 @@ steps:
       set -e
       cd $BUILD_SOURCESDIRECTORY
       git status --porcelain=v1
-      git diff --name-only --color-words
-      changed=$(git diff --name-only --ignore-all-space)
+      changed=$(git diff --name-only --ignore-space-change)
       echo "Changed files: $changed"
       for file in $changed; do
-        if [[ $(git diff --ignore-all-space "$file" | tail -n +5 | grep -c '^[+-]') -ne 0 ]]; then
-          echo "Text changes detected in $file. Pipeline failed."
-          exit 1
+        if [[ $(git diff --ignore-all-space -U0 "$file" | tail -n +5 | grep -c '^[+-]') -ne 0 ]]; then
+            echo "Text changes detected in $file. Pipeline failed."
+            git diff --ignore-all-space -U0 "$file"
+            exit 1
         fi
       done
       echo "No text changes detected. Continuing pipeline."
     workingDirectory: desktop
     displayName: Validate no files changed on build
+
 
 
   - template: ../common/publish-artifacts.yml
