Moved script over to Linux build

diff --git a/.vsts/linux/distribution.yml b/.vsts/linux/distribution.yml
--- a/.vsts/linux/distribution.yml
+++ b/.vsts/linux/distribution.yml
@@ -44,3 +44,14 @@ steps:
   - template: ../common/publish-artifacts.yml
     parameters:
       folder: linux
+
+  - script: |
+      set -e
+      changed=`git status | grep 'modified:' | wc -l`
+      if [ "$changed" -ne "0" ]; then
+        echo "Changes detected. Pipeline failed"
+        exit 1
+      fi
+    workingDirectory: desktop
+    displayName: Validate no files changed on build
+
